package Clases.Interfaz;
import Clases.*;
import java.util.HashMap;

/**
 *
 * @author Grupo 1
 */
public class PagoServicios extends javax.swing.JPanel {

    private MainAplicacion mainFrame; // Referencia al frame main de la aplicación
    
    private HashMap<String, HashMap<String, String>> servicios = new HashMap<>();

    /**
     * Crea el nuevo panel PagoServicios
     */
    public PagoServicios(MainAplicacion mainFrame) {
        initComponents();  
        this.mainFrame = mainFrame;
        initServicios();
        actualizarCampos();
    }

    private void initServicios() {
        // Agregar información de servicios
        agregarServicio("ANDE", "Número de Cliente ANDE", null);
        agregarServicio("Essap", "Número de Cliente Essap", "Número de Factura");
        agregarServicio("Claro", "Número de Cliente Claro", null);
        agregarServicio("Personal", "Número de Cliente Personal", "Número de Contrato");
        agregarServicio("Copaco", "Número de Cliente Copaco", "Número de Teléfono");
        agregarServicio("Gimnasio ABC", "Número de Socio", null);
    }
    
    private void agregarServicio(String nombre, String dato1, String dato2) {
        HashMap<String, String> servicio = new HashMap<>();
        servicio.put("Dato1", dato1);
        if (dato2 != null)
            servicio.put("Dato2", dato2);
        servicios.put(nombre, servicio);
        comboBoxServicios.addItem(nombre);
    }

    private void actualizarCampos() {
        String nombreServicioSeleccionado = (String) comboBoxServicios.getSelectedItem();
        if (nombreServicioSeleccionado != null) {
            HashMap<String, String> servicioSeleccionado = servicios.get(nombreServicioSeleccionado);
            if (servicioSeleccionado != null) {
                LabelDato1.setText(servicioSeleccionado.get("Dato1"));
                LabelDato2.setText(servicioSeleccionado.get("Dato2"));

                // Si no hay dato 2, ocultar LabelDato2 y campoDato2
                boolean mostrarDato2 = servicioSeleccionado.containsKey("Dato2") && !servicioSeleccionado.get("Dato2").isEmpty();
                LabelDato2.setVisible(mostrarDato2);
                campoDato2.setVisible(mostrarDato2);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSiguiente = new javax.swing.JButton();
        LabelDato1 = new javax.swing.JLabel();
        campoMontoAPagar = new javax.swing.JTextField();
        campoDato1 = new javax.swing.JTextField();
        comboBoxServicios = new javax.swing.JComboBox<>();
        campoDato2 = new javax.swing.JTextField();
        LabelDato2 = new javax.swing.JLabel();
        LabelTitulo = new javax.swing.JLabel();
        LabelServicio = new javax.swing.JLabel();
        LabelMonto = new javax.swing.JLabel();

        botonSiguiente.setBackground(new java.awt.Color(250, 230, 150));
        botonSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonSiguiente.setText("Siguiente");
        botonSiguiente.setToolTipText("");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        LabelDato1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelDato1.setText("Dato 1 (Dinamico)");

        campoMontoAPagar.setText("---.---.--");
        campoMontoAPagar.setToolTipText("");
        campoMontoAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMontoAPagarActionPerformed(evt);
            }
        });

        campoDato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDato1ActionPerformed(evt);
            }
        });

        comboBoxServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxServiciosActionPerformed(evt);
            }
        });

        campoDato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDato2ActionPerformed(evt);
            }
        });

        LabelDato2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelDato2.setText("Dato 2 (Dinamico)");

        LabelTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        LabelTitulo.setText("Pago de Servicios");

        LabelServicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelServicio.setText("Servicio");

        LabelMonto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelMonto.setText("Monto a Pagar (Gs.)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelDato1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LabelServicio, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(LabelMonto))
                                    .addComponent(LabelDato2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoDato2)
                                    .addComponent(comboBoxServicios, 0, 120, Short.MAX_VALUE)
                                    .addComponent(campoMontoAPagar)
                                    .addComponent(campoDato1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(LabelTitulo)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelServicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDato1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDato2)
                    .addComponent(campoDato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMonto)
                    .addComponent(campoMontoAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoMontoAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMontoAPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMontoAPagarActionPerformed

    private void campoDato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDato1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDato1ActionPerformed

    private void comboBoxServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxServiciosActionPerformed
        actualizarCampos();
    }//GEN-LAST:event_comboBoxServiciosActionPerformed

    private void campoDato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDato2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDato2ActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        boolean error = true;
        if (campoMontoAPagar.getText().matches("-?\\d+")){
            Integer monto = Integer.parseInt(campoMontoAPagar.getText());
            Cuenta cuenta = mainFrame.getCuenta();
            if (monto > 0 && cuenta != null && cuenta.tieneFondoSuficiente(monto)){
                Tarjeta tarjeta = cuenta.getTarjeta();
                String descripcion = String.valueOf(comboBoxServicios.getSelectedItem());
                descripcion += ", " + LabelDato1.getText() + ": " + campoDato1.getText();
                if (LabelDato2.isVisible()){
                    descripcion += ", " + LabelDato2.getText() + ": " + campoDato2.getText() + "  ";
                }
                boolean cerradoForzado = mainFrame.mostrarSolicitudDePinDeTransaccion();
                if (!cerradoForzado){
                    if (tarjeta.getClass().isInstance(TarjetaCredito.class)){
                        Sistema.pagarServicio(cuenta.getID(), monto, descripcion, "Tarjeta de Crédito");
                    }                
                    else{
                        Sistema.pagarServicio(cuenta.getID(), monto, descripcion, "Tarjeta de Débito");
                    }
                    error = false;
                }
            }
        }
        if (error){
            MensajeFracasoOperacion dialogoFracaso = new MensajeFracasoOperacion(mainFrame, true);
            dialogoFracaso.setLocationRelativeTo(this); // Centrar el diálogo en el marco principal
            dialogoFracaso.setVisible(true);     
        }
    }//GEN-LAST:event_botonSiguienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDato1;
    private javax.swing.JLabel LabelDato2;
    private javax.swing.JLabel LabelMonto;
    private javax.swing.JLabel LabelServicio;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JTextField campoDato1;
    private javax.swing.JTextField campoDato2;
    private javax.swing.JTextField campoMontoAPagar;
    private javax.swing.JComboBox<String> comboBoxServicios;
    // End of variables declaration//GEN-END:variables
}
