package Clases.Interfaz;
import Clases.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Grupo 1
 */
public class Transferencias extends javax.swing.JPanel {

    private MainAplicacion mainFrame; // Referencia al frame main de la aplicación
    
    /**
     * Crea el nuevo panel Transferencias
     */
    public Transferencias(MainAplicacion mainFrame) {
        initComponents();  
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botonSiguiente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nroCuentaDestinatario = new javax.swing.JTextField();
        documento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreApellido = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco Continental", "Itaú", "Banco GNB", "Sudameris Bank", "Banco Regional", "Banco Nacional de Fomento", "Banco Basa", "Banco Atlas", "Vision Banco", "Banco Familiar", "Financiera Paraguayo Japonés", "FIC SA de Finanzas", "Tu Financiera", "Financiera UENO", "Interfisa Banco" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Entidad");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Monto a Transferir (Gs.)");

        jTextField1.setText("---.---.---.--");
        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setText("Transferencias");

        botonSiguiente.setBackground(new java.awt.Color(250, 230, 150));
        botonSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonSiguiente.setText("Siguiente");
        botonSiguiente.setToolTipText("");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Nº Cuenta Destinatario");

        nroCuentaDestinatario.setText("Numero");
        nroCuentaDestinatario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nroCuentaDestinatarioFocusLost(evt);
            }
        });
        nroCuentaDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nroCuentaDestinatarioActionPerformed(evt);
            }
        });

        documento.setText("CI");
        documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Documento");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Nombre y Apellido Destinatario");

        nombreApellido.setText("Nombre");
        nombreApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreApellidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSiguiente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(documento)
                    .addComponent(jTextField1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, 160, Short.MAX_VALUE)
                    .addComponent(nroCuentaDestinatario)
                    .addComponent(nombreApellido))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(nroCuentaDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void nroCuentaDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nroCuentaDestinatarioActionPerformed

        actualizarDatosDestinatario();
    }//GEN-LAST:event_nroCuentaDestinatarioActionPerformed

    private void documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentoActionPerformed

    private void nombreApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreApellidoActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        // Validar los datos de la transferencia
        if(!jTextField1.getText().matches("-?\\d+") || Integer.parseInt(jTextField1.getText()) <= 0)
            JOptionPane.showMessageDialog(mainFrame, "El monto de transferencia no es valido!", "Error",  JOptionPane.ERROR_MESSAGE);   
        else if(!nroCuentaDestinatario.getText().matches("-?\\d+"))
            JOptionPane.showMessageDialog(mainFrame, "La entrada del numero de cuenta destinatario\n\t no es valido!", "Error",  JOptionPane.ERROR_MESSAGE);
        // Si no hay errores intentar realizar la  transferencia
        else
        {
            Integer monto = Integer.parseInt(jTextField1.getText());
            if (!mainFrame.getCuenta().tieneFondoSuficiente(monto)) {
                JOptionPane.showMessageDialog(mainFrame, 
                   "La cuenta no tiene fondos suficientes para la transferencia", "Error",  JOptionPane.ERROR_MESSAGE);
                return; 
            }         
            Integer idCuentaDestinatario = Integer.parseInt(nroCuentaDestinatario.getText());
            Cuenta cuentaDestinatario = Sistema.obtenerObjetoCuenta(idCuentaDestinatario);
            if(cuentaDestinatario == null)
                   JOptionPane.showMessageDialog(mainFrame, "La cuenta destinatario no existe!", "Error",  JOptionPane.ERROR_MESSAGE);
            else if(cuentaDestinatario.getTarjeta() instanceof TarjetaCredito)
                    JOptionPane.showMessageDialog(mainFrame, "No se puede realizar transferencias a cuentas de credito!", "Error",  JOptionPane.ERROR_MESSAGE);
            else
            {
                boolean cerradoForzado = mainFrame.mostrarSolicitudDePinDeTransaccion();
                if (!cerradoForzado){
                    Sistema.realizarTransferencia(mainFrame.getCuenta().getID(), idCuentaDestinatario, monto);
                }
            }
        }
       
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void nroCuentaDestinatarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nroCuentaDestinatarioFocusLost

        actualizarDatosDestinatario();
    }//GEN-LAST:event_nroCuentaDestinatarioFocusLost

    /**
     * Actualiza los datos del destinatario en base a su numero de cuenta en el sistema. 
     */
    public void actualizarDatosDestinatario() {
        if(nroCuentaDestinatario.getText().matches("-?\\d+"))
        {
            Integer idCuentaDestinatario = Integer.parseInt(nroCuentaDestinatario.getText());
            // Si la cuenta es la misma que la de la sesion actual tirar error, no podemos transferirnos a nosotros mismos
            if (idCuentaDestinatario == mainFrame.getCuenta().getID()) {
                nroCuentaDestinatario.setText("");
                nombreApellido.setText("");
                documento.setText("");
                JOptionPane.showMessageDialog(this, 
                        "¡No puedes transferirte a ti mismo!", "Error", JOptionPane.ERROR_MESSAGE);               
                return; 
            }
            
            Cuenta cuentaDestinatario = Sistema.obtenerObjetoCuenta(idCuentaDestinatario);
            if(cuentaDestinatario != null)
            {
                
               Cliente clienteDestino = Sistema.obtenerObjetoCliente(cuentaDestinatario.getIDPropietario());
                    if (clienteDestino != null) {
                        nombreApellido.setText(clienteDestino.getEtiqueta());
                        documento.setText(clienteDestino.getDocumento());
                    } else {
                      JOptionPane.showMessageDialog(this, 
                            "¡Cliente destino no existente!", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    
                
                   
            } else {
                  JOptionPane.showMessageDialog(this, 
                        "¡Cuenta de destinatario invalida!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JTextField documento;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nombreApellido;
    private javax.swing.JTextField nroCuentaDestinatario;
    // End of variables declaration//GEN-END:variables
}
